import Typewriter from "typewriter-effect";
import SideNavbar from "../components/SideNavbar";
import Image from "next/image";
import Head from "next/head";
import { SiGmail } from 'react-icons/si';
import { ImWhatsapp } from 'react-icons/im';
import { FaInstagram } from 'react-icons/fa';
import { CiFacebook } from 'react-icons/ci';

import yyy from '../public/yyy.gif';
import React from "react";
export default function Home() {
  return (
    <><><div className="bg-black">
      <Head>
        <title>MYSKILL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <SideNavbar />

      <div className="   text-white bg-black bg-cover pl-8 pt-1">
        {/* <img src="/online.jpg" alt="" /> */}
        < Image src="/d1.jpg" height={300} width={500} className="rounded--3xl pb-5" alt="Online learning Platform" />

      </div>
    </div>


      < >
        <div class="main">
          <Typewriter
            options={{
              strings: ["GOOGLE AMAZON META MICROSOFT APPLE"],
              autoStart: true,
              loop: true
            }} /><div>
            <span className=" font-mono  pt-2 bg-black bg-cover text-blue-400 text-center  text-2xl pl-1 transition-2s "> Hired Our Students
            </span>
          </div>
        </div>
      </><>
        <div class="main"><Typewriter
          options={{
            strings: ["SURPRISINGLY HOW HERE IS THE SECRET!"],
            autoStart: true,
            loop: true
          }} /><div>
            <span className="font-mono  bg-black text-blue-400 text-center   text-2xl pl-1 transition-2s">Enroll in Any Course That Might Excite You

            </span>

          </div>
        </div>
      </>
      <div className="flex bg-black pb-6 pt-5">
        {/* <Image src="file:///C:/Users/dell/Desktop/clone%20project/my-app/public/counsellor1.jpgg" height={90} width={200} alt="company" /> */}
        <button className="bg-blue-400 pointer-cursor z-0 text-white px-1  rounded-full text-2xl font-bold mt-10 ml-10 mr-10  animate-bounce "> ENROLL NOW
        </button>
        <Image src="/1675650541348.jpg" height={90} width={120} alt="company" />
      </div>
    </>

      <h3 className="text-2xl text-center text-serif pb-4  px-2 py-2 bg-blue-400  text-black  pl-15">Easy way to get Success Choose it or Regret Later !!

      </h3>
      < >
        <section className=" bg-black lg:flex flex-row  justify-center lg:justify-between items-center py-10">
          <div className="flex justify-center text-center">
            <div className="py-5 px-5 mx-auto ">
              <Image src='/XY.jpg'
                alt='User profile picture'
                width={400}
                height={110} />

              <h1 className="animate-pulse  text-serif text-white font-bold px-3 pt-6 h-300 text-2xl w-79  justify-between">Live 1:1 Doubt Support
              </h1 >
            </div>
          </div>

          <div className="flex justify-center text-center">
            <div className=" py-5 px-5 lg:pl-16">
              <Image src='/cert.jpg'
                alt='User profile picture'
                width={400}
                height={60}
                className="mx-auto"
              />
              <h1 className="text-serif font-bold animate-pulse  text-white  px-3 pt-7 h-300 text-2xl">Gain Certificate After Completion Of Course</h1>
            </div>
          </div>

          <div className="flex justify-center">

            <div className="pl-4">

              < Image src='/company.jpg'
                alt='User profile picture'
                width={400}
                height={60}
              />
              <h1 className=" animate-pulse  text-white text-serif font-bold px-3 py-25 h-300 pl-5 text-2xl pt-4 w-79 ">Get Placed At Your Dream Company
              </h1 >
            </div>
          </div>
        </section>
      </>

      <p className="text-2xl text-center font-serif  px-2 py-2  bg-blue-400 text-black pl-15">If You Are A working Professional Increase Your CTC Upto 1000%</p>


      <>
        <section className="justify-between bg-black grid grid-cols-1 lg:grid-cols-2 px-3 lg:px-24 py-16">

          <div className="flex justify-center py-5">
            <div className="flex lg:justify-center justify-center h-[78vh] md:h-[70vh] w-[30rem]">
              <div class=" bg-white rounded-lg p-8 flex-col mt-10 md:mt-0 relative z-10 shadow-md">
                <h2 class="text-gray-900 text-lg mb-1  font-medium title-font">Talk With Our Counsellor</h2>
                <p class="leading-relaxed mb-5 text-gray-600">This Will Help You To Grow More</p>
                <div class="relative mb-4">
                  <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
                  <input type="email" id="email" name="email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out"></input>
                </div>

                <div class="relative mb-4">
                  <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
                  <textarea id="message" name="message" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"></textarea>
                </div>
                <button class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 animate-bounce rounded text-lg">Get Started</button>
                <p class="text-xs text-gray-500 mt-3">Have Any Doubt Clear From The Best Counsellor Of India</p>
              </div>
            </div>
          </div>

          <div className="flex justify-center items-center py-5">

            <div className="flex justify-center h-[70vh] w-[25rem]">
              <div className="flex-row  relative pr-2 pb-3 py-5 w-full">
                < Image src={yyy} alt="my gif" fill={true} className="" />
              </div>
            </div>
          </div>

        </section>
      </>


      <div className="text-xl animate bg-black font-serif pr-8 justify-between flex-row space-y-3 md:flex pl-8 py-7 text-white ">

        <div className="flex justify-center items-center">

          <h2 className="text-xl  font-serif bg-black  text-white ">Contact Us</h2>
        </div>
        <div className="flex justify-center items-center">

          <h2 className="text-xl  font-serif bg-black  text-white ">Call Us</h2>
        </div>
        <div className="flex justify-center items-center">

          <p className="text-xl  font-serif bg-black  text-white"> 91+ 9924376136</p>
        </div>
        <div className="flex justify-center items-center">

          <h2 className="text-xl font-serif  bg-black text-white ">Write Us</h2>
        </div>
        <div className="flex justify-center items-center">

          <p className="text-xl font-serif  bg-black text-white ">Email US
          </p>
        </div>


      </div >

      <div className="">
        <h1 className=" bg-black text-3xl font-extrabold font-serif pt-5 text-center text-orange-500 py-2 pb-8">Lets Connect Via</h1>
        <div className=" text-white flex justify-center py-5 space-x-5 md:space-x-20  bg-black">
          <h1><SiGmail size="40" /></h1>
          <h1><ImWhatsapp size="40" /></h1>
          <h1><FaInstagram size="40" /></h1>
          <h1><CiFacebook size="40" /></h1>
        </div>

        <h1>

        </h1>
      </div>












    </>



  );
}



